#include "window.h"

using namespace clench::wsal;

std::map<UINT, KeyboardKeyCode> clench::wsal::win32KeyMap = {
	{ VK_BACK, KBKEY_BACKSPACE },
	{ VK_TAB, KBKEY_TAB },

	{ VK_CLEAR, KBKEY_CLEAR },
	{ VK_RETURN, KBKEY_RETURN },

	{ VK_PAUSE, KBKEY_PAUSE },
	{ VK_CAPITAL, KBKEY_CAPS_LOCK },

	{ VK_ESCAPE, KBKEY_ESC },

	{ VK_PRIOR, KBKEY_PAGEUP },
	{ VK_NEXT, KBKEY_PAGEDOWN },
	{ VK_END, KBKEY_END },
	{ VK_HOME, KBKEY_HOME },
	{ VK_LEFT, KBKEY_LEFT },
	{ VK_UP, KBKEY_UP },
	{ VK_RIGHT, KBKEY_RIGHT },
	{ VK_DOWN, KBKEY_DOWN },
	{ VK_SELECT, KBKEY_SELECT },
	{ VK_PRINT, KBKEY_PRINT },
	{ VK_EXECUTE, KBKEY_EXECUTE },
	{ VK_SNAPSHOT, KBKEY_PRINT_SCREEN },
	{ VK_INSERT, KBKEY_INSERT },
	{ VK_DELETE, KBKEY_DEL },
	{ VK_HELP, KBKEY_HELP },

	{ VK_LWIN, KBKEY_LSUPER },
	{ VK_RWIN, KBKEY_RSUPER },
	{ VK_APPS, KBKEY_APPS },

	{ VK_NUMPAD0, KBKEY_NUMPAD0 },
	{ VK_NUMPAD1, KBKEY_NUMPAD1 },
	{ VK_NUMPAD2, KBKEY_NUMPAD2 },
	{ VK_NUMPAD3, KBKEY_NUMPAD3 },
	{ VK_NUMPAD4, KBKEY_NUMPAD4 },
	{ VK_NUMPAD5, KBKEY_NUMPAD5 },
	{ VK_NUMPAD6, KBKEY_NUMPAD6 },
	{ VK_NUMPAD7, KBKEY_NUMPAD7 },
	{ VK_NUMPAD8, KBKEY_NUMPAD8 },
	{ VK_NUMPAD9, KBKEY_NUMPAD9 },
	{ VK_MULTIPLY, KBKEY_NUMPAD_MUL },
	{ VK_ADD, KBKEY_NUMPAD_ADD },
	{ VK_SEPARATOR, KBKEY_NUMPAD_DIV },
	{ VK_DECIMAL, KBKEY_NUMPAD_DOT },
	{ VK_DIVIDE, KBKEY_NUMPAD_DIV },

	{ VK_F1, KBKEY_F1 },
	{ VK_F2, KBKEY_F2 },
	{ VK_F3, KBKEY_F3 },
	{ VK_F4, KBKEY_F4 },
	{ VK_F5, KBKEY_F5 },
	{ VK_F6, KBKEY_F6 },
	{ VK_F7, KBKEY_F7 },
	{ VK_F8, KBKEY_F8 },
	{ VK_F9, KBKEY_F9 },
	{ VK_F10, KBKEY_F10 },
	{ VK_F11, KBKEY_F11 },
	{ VK_F12, KBKEY_F12 },

	{ VK_NUMLOCK, KBKEY_NUM_LOCK },
	{ VK_SCROLL, KBKEY_SCROLL_LOCK },

	{ VK_LMENU, KBKEY_LMENU },
	{ VK_RSHIFT, KBKEY_RSHIFT },
	{ VK_LSHIFT, KBKEY_LSHIFT },
	{ VK_RSHIFT, KBKEY_RSHIFT },
	{ VK_LCONTROL, KBKEY_LCTRL },
	{ VK_RCONTROL, KBKEY_RCTRL }
};
